# Generated by Django 4.0.4 on 2022-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_song_liked_song_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
