# Generated by Django 4.0.4 on 2022-04-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0003_song_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='num_likes',
            field=models.IntegerField(null=True),
        ),
    ]
